// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID     string `json:"_id"`
	Title  string `json:"TITLE"`
	Author string `json:"AUTHOR"`
	Price  int    `json:"PRICE"`
}

type CreateBookInput struct {
	Title  string `json:"TITLE"`
	Author string `json:"AUTHOR"`
	Price  int    `json:"PRICE"`
}

type DeleteBookResponse struct {
	DeleteBookID string `json:"deleteBookID"`
}

type UpdateBookInput struct {
	Title  *string `json:"TITLE,omitempty"`
	Author *string `json:"AUTHOR,omitempty"`
	Price  *int    `json:"PRICE,omitempty"`
}
